In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# сгенерируем набор данных
data, target, coef = datasets.make_regression(n_samples=1000, n_features = 2, n_informative = 2, n_targets = 1, 
                                              noise = 5, coef = True, random_state = 2)

In [3]:
X = data.T.copy()
y = target.copy()
coef

array([62.6735955, 68.0472182])

In [4]:
# реализуем функцию, определяющую среднеквадратичную ошибку
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [5]:
def eval_model(X, y, iterations, alpha=1e-4):
    r_eval = []
    a = []
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if i % (iterations / 10) == 0:
            print(i, W, err)
        r_eval.append([i, err])
    r_eval  = np.asarray(r_eval)        
    return W, r_eval

In [6]:
r_eval = np.array([])
W_eval, r_eval = eval_model(X, y, iterations=1000, alpha=1e-2)
W_eval

100 [53.4130283  58.48118215] 200.6550957638899
200 [61.01943017 66.86800539] 30.104339574270313
300 [62.13608435 68.07620103] 26.503591646200096
400 [62.29985058 68.25040066] 26.427546006207947
500 [62.32384693 68.2755367 ] 26.425939537855726
600 [62.32736031 68.27916629] 26.425905593716312
700 [62.32787435 68.27969074] 26.42590487636044
800 [62.32794952 68.27976656] 26.425904861198063
900 [62.3279605  68.27977753] 26.42590486087754
1000 [62.32796211 68.27977912] 26.42590486087076


array([62.32796211, 68.27977912])

In [7]:
def eval_sgd_model(X, y, iterations, qty_in_batch=1, alpha=1e-4):
    r_sgb = []
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    n_batch = n // qty_in_batch
    if n % qty_in_batch != 0:
        n_batch += 1
    for i in range(1, iterations+1):
        for b in range(n_batch):
            start_ = qty_in_batch*b
            end_ = qty_in_batch*(b+1)

            # print(b, n_batch, start_, end_)

            X_tmp = X[:, start_ : end_]
            y_tmp = y[start_ : end_]
            y_pred_tmp = np.dot(W, X_tmp)
            err = calc_mse(y_tmp, y_pred_tmp)
            W -= (alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp.T)))

        if i % (iterations / 10) == 0:
            print(i, W, err)
        r_sgb.append([i, err])
    r_sgb  = np.asarray(r_sgb)
    return W, r_sgb

In [10]:
r_sgb = np.array([])
w_sgb, r_sgb = eval_sgd_model(X, y, iterations=1000, qty_in_batch=10, alpha=1e-2)
w_sgb

100 [53.1734     58.46646873] 66.54336655393843
200 [60.96095348 66.83749786] 24.958858479117033
300 [62.12348759 68.06718073] 27.400945031395025
400 [62.29689015 68.24794985] 27.94930874871403
500 [62.3227359  68.27454154] 28.034304535873396
600 [62.32658573 68.27845566] 28.04693265551564
700 [62.32715884 68.27903212] 28.048798024963993
800 [62.32724411 68.27911706] 28.049073411777194
900 [62.3272568  68.27912958] 28.04911407466735
1000 [62.32725868 68.27913143] 28.049120080430402


array([62.32725868, 68.27913143])